name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-2-cache-v1-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn install --immutable
      - name: build
        run: yarn run build
      - name: test
        run: yarn test
